# Generated by Django 4.2.5 on 2023-10-02 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=50)),
                ('id_professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalapp.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('id_dsciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalapp.disciplina')),
            ],
        ),
    ]
