# Generated by Django 4.2.5 on 2023-10-02 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='id_dsciplina',
            new_name='disciplina',
        ),
        migrations.RenameField(
            model_name='disciplina',
            old_name='id_professor',
            new_name='professor',
        ),
    ]
