# Generated by Django 4.2.5 on 2023-10-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0002_rename_id_dsciplina_aluno_disciplina_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='professor',
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
        migrations.DeleteModel(
            name='Disciplina',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
