# Generated by Django 4.2.5 on 2023-10-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0004_professor_disciplina_aluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='dataTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.CharField(max_length=100)),
                ('professor', models.CharField(max_length=100)),
                ('materia', models.CharField(max_length=100)),
            ],
        ),
    ]
