# Generated by Django 4.2.5 on 2023-10-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0005_datatable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatable',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
